var BRICK = 1;
var SPACE = 2;

// Default map (every map has 13 horizontal grids and 13 vertical grids)
var landMap = [
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE,
    SPACE, SPACE,
  ],
  [SPACE, SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, BRICK, BRICK, BRICK,
    SPACE, BRICK, SPACE,
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, SPACE,
  ],
  [SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, SPACE,
    SPACE, SPACE, SPACE
  ],
  [BRICK, BRICK, SPACE, SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE,
    SPACE, BRICK, BRICK,
  ],
  [BRICK, SPACE, SPACE, SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK,
    SPACE, SPACE, BRICK,
  ],
  [SPACE, SPACE, BRICK, SPACE, BRICK, BRICK, SPACE, SPACE, BRICK, SPACE,
    SPACE, SPACE, BRICK,
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, SPACE, SPACE, SPACE, BRICK, SPACE,
    BRICK, SPACE, BRICK,
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, BRICK,
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, SPACE,
    BRICK, SPACE, BRICK,
  ],
  [SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, SPACE,
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, BRICK,
    BRICK, SPACE, SPACE,
  ],
  [SPACE, SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE, SPACE,
    SPACE, SPACE,
  ],
];

// the first map array (consist of spaces & bricks)
var landMap1 = [
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE,
    SPACE, SPACE,
  ],
  [SPACE, SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, BRICK, BRICK, BRICK,
    SPACE, BRICK, SPACE,
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, SPACE,
  ],
  [SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, SPACE,
    SPACE, SPACE, SPACE
  ],
  [BRICK, BRICK, SPACE, SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE,
    SPACE, BRICK, BRICK,
  ],
  [BRICK, SPACE, SPACE, SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK,
    SPACE, SPACE, BRICK,
  ],
  [SPACE, SPACE, BRICK, SPACE, BRICK, BRICK, SPACE, SPACE, BRICK, SPACE,
    SPACE, SPACE, BRICK,
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, SPACE, SPACE, SPACE, BRICK, SPACE,
    BRICK, SPACE, BRICK,
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, BRICK,
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, SPACE,
    BRICK, SPACE, BRICK,
  ],
  [SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, SPACE,
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, BRICK,
    BRICK, SPACE, SPACE,
  ],
  [SPACE, SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE, SPACE,
    SPACE, SPACE,
  ],
];

// the second map array
var landMap2 = [
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE,
    SPACE, SPACE
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, BRICK, SPACE, BRICK, BRICK, BRICK,
    SPACE, SPACE, SPACE
  ],
  [BRICK, BRICK, SPACE, SPACE, BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE,
    BRICK, SPACE
  ],
  [BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, SPACE, SPACE, SPACE,
    SPACE, BRICK, SPACE
  ],
  [SPACE, SPACE, SPACE, SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE,
    BRICK, BRICK, BRICK
  ],
  [BRICK, SPACE, BRICK, SPACE, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE,
    SPACE, SPACE, BRICK
  ],
  [SPACE, SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE, BRICK, SPACE,
    SPACE, SPACE, BRICK
  ],
  [SPACE, SPACE, BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, SPACE,
    BRICK, SPACE, BRICK
  ],
  [SPACE, SPACE, BRICK, SPACE, SPACE, BRICK, SPACE, SPACE, BRICK, SPACE, BRICK,
    SPACE, BRICK
  ],
  [SPACE, BRICK, BRICK, SPACE, SPACE, BRICK, SPACE, SPACE, SPACE, SPACE,
    BRICK, SPACE, BRICK
  ],
  [SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE, SPACE, BRICK,
    SPACE, SPACE
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    BRICK, SPACE, SPACE
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE,
    SPACE, BRICK
  ],
];

// the third map array
var landMap3 = [
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE,
    BRICK, BRICK
  ],
  [SPACE, BRICK, BRICK, BRICK, BRICK, SPACE, SPACE, BRICK, BRICK, SPACE,
    BRICK, BRICK, SPACE
  ],
  [SPACE, BRICK, SPACE, SPACE, SPACE, SPACE, BRICK, BRICK, SPACE, SPACE, BRICK,
    SPACE, SPACE
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE,
    SPACE, SPACE, BRICK
  ],
  [BRICK, SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE,
    SPACE, BRICK, BRICK
  ],
  [BRICK, SPACE, SPACE, SPACE, SPACE, BRICK, BRICK, SPACE, BRICK, BRICK,
    SPACE, BRICK, BRICK
  ],
  [SPACE, SPACE, BRICK, SPACE, BRICK, BRICK, SPACE, SPACE, BRICK, SPACE,
    SPACE, SPACE, SPACE
  ],
  [SPACE, BRICK, BRICK, SPACE, BRICK, SPACE, SPACE, SPACE, BRICK, SPACE,
    BRICK, SPACE, SPACE
  ],
  [SPACE, BRICK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, SPACE, BRICK,
    SPACE, BRICK
  ],
  [SPACE, BRICK, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE, SPACE,
    BRICK, SPACE, BRICK
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK,
    SPACE, SPACE
  ],
  [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BRICK, SPACE, BRICK, SPACE,
    BRICK, SPACE, SPACE
  ],
  [SPACE, BRICK, BRICK, SPACE, SPACE, SPACE, BRICK, BRICK, BRICK, SPACE, SPACE,
    SPACE, SPACE
  ],
];


// assigned the position of tank & created containers for map's blocks
var tankMap = [ [0, 0] ]
function prepareMap() {
  this.position = 0;
  for (var i = 0; i < 13; i++) {
    for (var j = 0; j < 13; j++) {
      position = i + "" + j;
      var block = document.createElement('div');
      document.getElementById("divMap").appendChild(block);
      block.id = position;
    }
  }
}

// method to initialize tanks placed on map
function loadTanks() {
  var myTankX = tankMap[0][0];
  var myTankY = tankMap[0][1];
  myTank = new MyTank(myTankX, myTankY);
  myTank.createTank();
}

// method to initialize game's land map
function loadMap() {
  var block;
  for (var i = 0; i < 13; i++) {
    for (var j = 0; j < 13; j++) {
      var type = landMap[j][i];
      switch (type) {
        case BRICK:
          block = new Brick(i, j);
          break
        case SPACE:
          block = new Space(i, j);
          break
        default:
          break
      }
      block.createBlock();
    }
  }
}